### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [alecthomas/units#3]
Please use semantic versioning:
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by alecthomas** [comment]
Several points:
- Most developers know what semantic versioning is, so explaining it is not that helpful.
- You would be better served by linking to solutions that make semver possible with Go. eg. gopkg.in
- I already use semantic versioning for [some of](https://gopkg.in/alecthomas/kingpin.v2) my projects.
- I don't use it on others because the maintenance overhead is non-zero. This is one of those projects.

**Comment by petercolberg** [comment]
On the contrary, many Go developers have not used semantic versioning before and are happy to start tagging releases. Of course, there is also a handful of Go developers that reject tagging releases due to the perceived overhead of following well-established practices in software engineering.

**Comment by petercolberg** [comment]
Debian packages each Go package repository as a separate Debian source package. In this case, your package has been [included in Debian](https://packages.debian.org/sid/golang-github-alecthomas-units-dev) as an implicit dependency of [acmetool](https://github.com/hlandau/acme). The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

All you would have to do is regularly tag releases, which yields handy Debian package versions and makes it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.

**Comment by shawnps-sigsci** [comment]
@alecthomas any chance you could tag a release?
